### ISSUE TITLE
Do you happen to achieve real time answers ?

### ISSUE THREAD

**Issue by tony-wolff** [GraesonB/ChatGPT-Wrapper-For-Unity#21]
Hey really great project !
Right now for my project I'm using this tool because it's handy. However it takes a bit time to get the answer from OpenAI, I don't know how to speed up things. on OpenAi playground the answers are real-time, the same for the chatGPT website.
I understand it their tech and it is hosted on their website, so there is nothing we can do.
OR maybe I'm doing something really bad and unoptimized and that's why I don't get real time answers.

**Comment by SeanBannister** [comment]
Funnily enough I just came here to check if this code supported "streaming", the ChatGPT API allows you to parse a [boolean called "stream"](https://platform.openai.com/docs/api-reference/chat/create#chat/create-stream) which then streams the results back to you rather than waiting for the entire chat to complete which really speeds things up. I just checked the code and this doesn't currently have streaming implemented.

**Comment by tony-wolff** [comment]
Hey thank you for the information !
I hope this repo will add the streaming functionality.
@SeanBannister another repo/code that allows streaming ?

**Comment by GraesonB** [comment]
Sorry @tony-wolff, I'm not actively updating this repo currently. It might be hard for me to find time to add streaming support.

**Comment by SeanBannister** [comment]
I did do a little research to see what else was out there but haven't had a chance to test anything, this one supports streaming according to its changelog https://github.com/mochi-neko/ChatGPT-API-unity
