### ISSUE TITLE
: HTTP Error: HTTP/1.1 400 Bad Request

### ISSUE THREAD

**Issue by Deeper-wk** [GraesonB/ChatGPT-Wrapper-For-Unity#5]
I used your code to build and run, and the effect is very good! However, after about 8 to 9 conversations, a protocol error occurred in Request.cs: HTTP Error: HTTP/1.1 400 Bad Request
After that, the message will not be received. I don't know much about the network, so I want to ask if there are any solutions or ideas?
Thank you for your code
The version I use is 2021.3.7f1c1
<img width="531" alt="8172a9133119961e9f2f4b6b99a9218" src="https://user-images.githubusercontent.com/85387275/222029941-d769e80b-26a0-457e-8d8a-878674557789.png">

**Comment by GraesonB** [comment]
I suppose that error message isn't very revealing, however, im 99% sure that max_tokens is the culprit here.

Essentially how this wrapper works is it keeps appending user responses and GPT responses and makes one big string and sends it off to OpenAI's API. So the longer the conversation, the bigger the string. OpenAI sets a limit on the amount of tokens that you can send in one request, you can find the limits for each model here:

https://platform.openai.com/docs/models/gpt-3

At the moment I don't have a good solution for this, but a temporary solution might be the just chop off the earliest messages to make room for new messages in the conversation, but if you do that you might lose some important context. I can work on implementing that at some point this week. :-)

**Comment by Deeper-wk** [comment]
Thank you. I will continue to pay attention to your project
：）

**Comment by Deeper-wk** [comment]
I just noticed that the language I used to talk with gpt in the project is Chinese/I'm from China
So when I have a conversation in Chinese for 8 to 9 times, http: 400 appears
However, when I was just communicating in English, I tested 25 conversations without any errors (I was actually testing a word adventure game)
So I wonder if it's related to language

**Comment by GraesonB** [comment]
I see, I just added better error messages on API responses along with support for the new official ChatGPT API. Please test it out and give me feedback!
